# Generated by Django 4.1.3 on 2022-12-05 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0003_remove_post_like_like"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="follow",
        ),
    ]
