# Generated by Django 4.1.3 on 2022-12-09 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0004_remove_user_follow"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="following",
            unique_together={("follower", "followee")},
        ),
    ]
