# Generated by Django 4.1.3 on 2022-12-12 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0006_alter_post_creator"),
    ]

    operations = [
        migrations.AlterField(
            model_name="like",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to="network.post",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="like",
            unique_together={("creator", "post")},
        ),
    ]
