name: Testing
on: push

jobs:
  test_project:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run Django unit tests
      run: |
        pip3 install --user django
        pip3 install --user django-livereload-server
        python3 manage.py test
